Test case Hedgehog often overlooks
We deliberately introduce an error, and Hedgehog manages to often
overlook it. Also, when it tries to format the counterexample for
`SFixed 0 1` or `SFixed 1 0`, it experiences:

Exception: divide by zero

which by the way is unrelated but also a bug somewhere.